//chatGpt generated 'Array of dairy Products'
export default [
  "Milk",
  "Cheese",
  "Yogurt",
  "Butter",
  "Cream",
  "Sour Cream",
  "Cottage Cheese",
  "Cream Cheese",
  "Whipped Cream",
  "Ice Cream",
  "Frozen Yogurt",
  "Mascarpone",
  "Ricotta",
  "Parmesan",
  "Cheddar",
  "Mozzarella",
  "Swiss Cheese",
  "Gouda",
  "Brie",
  "Camembert",
  "Blue Cheese",
  "Feta",
  "Goat Cheese",
  "Havarti",
  "Provolone",
  "Gruyère",
  "Colby",
  "Monterey Jack",
  "Pepper Jack",
  "Gorgonzola",
  "Roquefort",
  "Fontina",
  "Emmental",
  "Manchego",
  "Halloumi",
  "Paneer",
  "Quark",
  "Kefir",
  "Sour Milk",
  "Condensed Milk",
  "Evaporated Milk",
  "Powdered Milk",
  "Buttermilk",
  "Whey",
  "Lactose-Free Milk",
  "Almond Milk",
  "Soy Milk",
  "Coconut Milk",
  "Rice Milk",
  "Oat Milk",
];
