//chatGpt generated 'Array of 50 liquid forms of dairy Products'
export default [
  "Whole Milk",
  "Skim Milk",
  "2% Milk",
  "Chocolate Milk",
  "Buttermilk",
  "Heavy Cream",
  "Light Cream",
  "Half-and-Half",
  "Condensed Milk",
  "Evaporated Milk",
  "Sweetened Condensed Milk",
  "Unsweetened Condensed Milk",
  "Whipping Cream",
  "Single Cream",
  "Double Cream",
  "Clotted Cream",
  "Sour Cream",
  "Creme Fraiche",
  "Cream Cheese",
  "Mascarpone",
  "Greek Yogurt",
  "Regular Yogurt",
  "Kefir",
  "Buttercream",
  "Ghee",
  "Whey",
  "Lactose-Free Milk",
  "Almond Milk",
  "Coconut Milk",
  "Cashew Milk",
  "Oat Milk",
  "Soy Milk",
  "Rice Milk",
  "Hemp Milk",
  "Macadamia Milk",
  "Hazelnut Milk",
  "Quinoa Milk",
  "Peanut Milk",
  "Sunflower Seed Milk",
  "Flax Milk",
  "Pea Milk",
  "Potato Milk",
  "Tapioca Milk",
  "Sesame Milk",
  "Buckwheat Milk",
  "Barley Milk",
  "Spelt Milk",
  "Walnut Milk",
  "Pistachio Milk",
  "Pecan Milk",
];
