export default [
    "Green Acres Farm",
    "Golden Harvest Farm",
    "Sunny Meadows Farm",
    "Happy Valley Farm",
    "Maple Tree Farm",
    "Oak Ridge Farm",
    "Pine Hollow Farm",
    "River Bend Farm",
    "Blue Sky Farm",
    "Windy Hill Farm",
    "Sunrise Farm",
    "Moonlight Farm",
    "Starlight Farm",
    "Rainbow Farm",
    "Misty Morning Farm",
    "Whispering Pines Farm",
    "Hidden Valley Farm",
    "Prairie View Farm",
    "Hilltop Farm",
    "Valley View Farm",
    "Apple Blossom Farm",
    "Peach Tree Farm",
    "Berry Patch Farm",
    "Grapevine Farm",
    "Cedar Creek Farm",
    "Willowbrook Farm",
    "Wildflower Farm",
    "Country Charm Farm",
    "Silver Creek Farm",
    "Golden Fields Farm",
    "Green Pastures Farm",
    "Heritage Farm",
    "Clearview Farm",
    "Evergreen Farm",
    "Fairview Farm",
    "Highland Farm",
    "Meadow Brook Farm",
    "Mountain View Farm",
    "North Star Farm",
    "Old Mill Farm",
    "Pioneer Farm",
    "Rocky Ridge Farm",
    "Rosewood Farm",
    "Springfield Farm",
    "Stony Brook Farm",
    "Sunset Ridge Farm",
    "Sweetwater Farm",
    "Twin Oaks Farm",
    "Whitetail Farm",
    "Winterfell Farm",
];
