export default [
    "Cheddar Cheese",
    "Mozzarella Cheese",
    "Swiss Cheese",
    "Parmesan Cheese",
    "Feta Cheese",
    "Gouda Cheese",
    "Havarti Cheese",
    "Colby Cheese",
    "Monterey Jack Cheese",
    "Provolone Cheese",
    "Blue Cheese",
    "Brie Cheese",
    "Camembert Cheese",
    "Gruyere Cheese",
    "Edam Cheese",
    "Asiago Cheese",
    "Roquefort Cheese",
    "Manchego Cheese",
    "Emmental Cheese",
    "Cottage Cheese",
    "Paneer",
    "Quark",
    "Ricotta Cheese",
    "Halloumi Cheese",
    "Fontina Cheese",
    "Pepper Jack Cheese",
    "Limburger Cheese",
    "Muenster Cheese",
    "Gorgonzola Cheese",
    "Brick Cheese",
    "Chevre (Goat Cheese)",
    "Boursin Cheese",
    "Stilton Cheese",
    "Taleggio Cheese",
    "Jarlsberg Cheese",
    "Raclette Cheese",
    "Saint-Nectaire Cheese",
    "Beaufort Cheese",
    "Saint-Paulin Cheese",
    "Belper Knolle",
    "Red Leicester Cheese",
    "Wensleydale Cheese",
    "Caerphilly Cheese",
    "Sbrinz Cheese",
    "Burrata Cheese",
    "Cotija Cheese",
    "Halloumi Cheese",
    "Provoleta Cheese",
    "Kefalograviera Cheese",
    "Port Salut Cheese",
];
