export default [
    "Apple",
    "Banana",
    "Orange",
    "Grapes",
    "Strawberry",
    "Watermelon",
    "Pineapple",
    "Mango",
    "Kiwi",
    "Peach",
    "Pear",
    "Cherry",
    "Blueberry",
    "Raspberry",
    "Blackberry",
    "Plum",
    "Apricot",
    "Cantaloupe",
    "Honeydew",
    "Lemon",
    "Lime",
    "Pomegranate",
    "Coconut",
    "Papaya",
    "Fig",
    "Guava",
    "Lychee",
    "Passion Fruit",
    "Dragon Fruit",
    "Star Fruit",
    "Kumquat",
    "Tangerine",
    "Nectarine",
    "Cranberry",
    "Rhubarb",
    "Persimmon",
    "Jackfruit",
    "Mangosteen",
    "Clementine",
    "Blackcurrant",
    "Gooseberry",
    "Elderberry",
    "Bilberry",
    "Cranberry",
    "Feijoa",
    "Loquat",
    "Quince",
    "Satsuma",
    "Ugli Fruit",
    "Yuzu",
];
